.DEFAULT_GOAL := all
ROOT_MAKEFILE := $(abspath $(lastword $(MAKEFILE_LIST)))
PROJECT_ROOT := $(patsubst %/,%,$(dir $(ROOT_MAKEFILE)))

GO_TOOLS ?= $(filter-out $(GO_PKG_BETTERALIGN) $(GO_PKG_GRIT),$(GO_TOOLS_DEFAULT))
GO_MODULE_SLUGS_NO_BETTERALIGN ?= $(GO_MODULE_SLUGS)

GO_MODULE_SLUGS_USE_DEADCODE = $(GO_MODULE_SLUGS)
DEADCODE_IGNORE_PATTERNS_FILE = .deadcodeignore
DEADCODE_ERROR_ON_UNIGNORED = true
DEADCODE_FLAGS = -test

include $(PROJECT_ROOT)/make/go.mk
include $(PROJECT_ROOT)/make/integration.mk
